---
- name: Validate required parameters
  fail:
    msg: "Parameter {{ item }} is required but not provided"
  when: vars[item] is undefined or vars[item] == ""
  loop:
    - disk
    - mount_destination
  tags: create_lvm

- name: Check if disk exists
  stat:
    path: "{{ full_disk_path }}"
  register: disk_check
  tags: create_lvm

- name: Fail if disk does not exist
  fail:
    msg: "Disk {{ full_disk_path }} does not exist"
  when: not disk_check.stat.exists
  tags: create_lvm

- name: Install LVM2 package
  package:
    name: lvm2
    state: present
  tags: create_lvm

- name: Check if disk is already used in LVM
  shell: "pvdisplay {{ full_disk_path }} 2>/dev/null | grep -q 'VG Name' && echo 'used' || echo 'free'"
  register: disk_lvm_status
  changed_when: false
  failed_when: false
  tags: create_lvm

- name: Warning if disk is already in use
  debug:
    msg: "WARNING: Disk {{ full_disk_path }} is already used in LVM. Use force_create=true to override."
  when: 
    - disk_lvm_status.stdout == "used"
    - not force_create
  tags: create_lvm

- name: Fail if disk is in use and force_create is false
  fail:
    msg: "Disk {{ full_disk_path }} is already used in LVM. Set force_create=true to override."
  when: 
    - disk_lvm_status.stdout == "used"
    - not force_create
  tags: create_lvm

- name: Create physical volume
  lvg:
    vg: "{{ volume_group_name }}"
    pvs: "{{ full_disk_path }}"
    state: present
  tags: create_lvm

- name: Check if logical volume already exists
  shell: "lvdisplay /dev/{{ volume_group_name }}/{{ logical_volume_name }} 2>/dev/null && echo 'exists' || echo 'not_exists'"
  register: lv_check
  changed_when: false
  failed_when: false
  tags: create_lvm

- name: Create logical volume using all available space
  lvol:
    vg: "{{ volume_group_name }}"
    lv: "{{ logical_volume_name }}"
    size: "100%FREE"
    state: present
  when: lv_check.stdout == "not_exists"
  tags: create_lvm

- name: Create filesystem on logical volume
  filesystem:
    fstype: "{{ filesystem_type }}"
    dev: "{{ lvm_device_path }}"
  tags: create_lvm

- name: Check if mount destination exists
  stat:
    path: "{{ mount_destination }}"
  register: mount_dir_check
  tags: create_lvm

- name: Display mount directory status
  debug:
    msg: |
      Mount destination: {{ mount_destination }}
      {% if mount_dir_check.stat.exists %}
      Directory already exists: {{ mount_dir_check.stat.isdir }}
      {% else %}
      Directory will be created
      {% endif %}
  tags: create_lvm

- name: Create mount directory with proper permissions
  file:
    path: "{{ mount_destination }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
    recurse: yes
  tags: create_lvm

- name: Check if mount destination is already mounted
  shell: "mountpoint -q {{ mount_destination }} && echo 'mounted' || echo 'not_mounted'"
  register: mount_check
  changed_when: false
  failed_when: false
  tags: create_lvm

- name: Display mount status
  debug:
    msg: |
      Mount point {{ mount_destination }} status: {{ mount_check.stdout }}
      {% if mount_check.stdout == 'mounted' %}
      ⚠️  Directory is already mounted - will skip mounting
      {% else %}
      ✅ Ready to mount LVM volume
      {% endif %}
  tags: create_lvm

- name: Backup /etc/fstab
  copy:
    src: /etc/fstab
    dest: "/etc/fstab.backup.{{ ansible_date_time.epoch }}"
    remote_src: yes
  when: backup_fstab
  tags: create_lvm

- name: Add entry to /etc/fstab and mount
  mount:
    path: "{{ mount_destination }}"
    src: "{{ lvm_device_path }}"
    fstype: "{{ filesystem_type }}"
    opts: defaults
    state: mounted
  when: mount_check.stdout == 'not_mounted'
  notify:
    - Reload systemd daemon
  tags: create_lvm

- name: Add to fstab only (when already mounted)
  mount:
    path: "{{ mount_destination }}"
    src: "{{ lvm_device_path }}"
    fstype: "{{ filesystem_type }}"
    opts: defaults
    state: present
  when: mount_check.stdout == 'mounted'
  tags: create_lvm

- name: Verify mount is successful
  command: "df -h {{ mount_destination }}"
  register: mount_verification
  changed_when: false
  tags: create_lvm

- name: Get current volume group information
  shell: "LANG=C vgdisplay {{ volume_group_name }} | grep 'VG Size' | awk '{print $3, $4}'"
  register: vg_size_info
  changed_when: false
  tags: create_lvm

- name: Display LVM creation summary
  debug:
    msg: |
      === LVM CREATION SUMMARY ===
      Host: {{ inventory_hostname }}
      Disk used: {{ full_disk_path }}
      Volume Group: {{ volume_group_name }}
      Logical Volume: {{ logical_volume_name }}
      Device Path: {{ lvm_device_path }}
      Filesystem: {{ filesystem_type }}
      Mount Point: {{ mount_destination }}
      Volume Group Size: {{ vg_size_info.stdout }}
      
      Mount verification:
      {{ mount_verification.stdout }}
      
      ✅ LVM setup completed successfully!
  tags: create_lvm

- name: Create summary fact
  set_fact:
    lvm_creation_summary:
      hostname: "{{ inventory_hostname }}"
      disk_used: "{{ full_disk_path }}"
      volume_group: "{{ volume_group_name }}"
      logical_volume: "{{ logical_volume_name }}"
      device_path: "{{ lvm_device_path }}"
      filesystem_type: "{{ filesystem_type }}"
      mount_point: "{{ mount_destination }}"
      vg_size: "{{ vg_size_info.stdout }}"
      creation_date: "{{ ansible_date_time.iso8601 }}"
  tags: create_lvm
