---
galaxy_info:
  author: Marek
  description: Role for creating LVM volume groups and logical volumes with automatic mounting
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: RedHat
      versions:
        - 7
        - 8
        - 9

dependencies: []
